---

- name: Check server uptime
  shell: cat /proc/uptime
  register: host_uptime
  changed_when: false
  tags:
    - packages

- name: Update cache if server has been up less than an hour
  become: yes
  apt:
    update_cache: yes
    # Make idempotency test happy
    cache_valid_time: 60
  when: "(host_uptime.stdout_lines[0].split(' ')[0] | int ) / 3600 < 1"
  tags:
    - packages

- name: Updating cache if it has been a while
  become: yes
  apt:
    update_cache: yes
    cache_valid_time: "{{ cache_valid_time }}"
  tags:
    - packages

# Uses a group name to look for a list to combine with base_packages.
- name: Install Base Packages and any packages defined per Host Group
  become: yes
  apt:
    name: "{{ base_packages | union(lookup('vars', item + '_group_packages', default=[])) }}"
    state: present
  with_items: "{{ group_names }}"
  tags:
    - packages

- name: Ensure packages are removed if requested
  become: yes
  apt:
    name: "{{ packages_to_remove }}"
    state: absent
    purge: yes
  when: packages_to_remove is defined
  tags:
    - packages
